tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

brew "stow"
brew "gpg"
brew "asdf"
brew "coreutils"
brew "curl"
brew "git"
brew "starship"
brew "watchman"
brew "cocoapods"
brew "ffmpeg"
brew "yt-dlp"

cask "google-japanese-ime"
cask "google-chrome"
sask "brave-browser"
cask "tor-browser"
cask "alfred"
cask "clipy"
cask "spectacle"
cask "cleanmymac"
cask "clip-studio-paint"
cask "dropbox"
cask "google-drive"
cask "1password"
cask "visual-studio-code"
cask "intellij-idea"
cask "iterm2"
cask "tableplus"
cask "wireshark"
cask "docker"
cask "insomnia"
cask "keybase"
cask "blender"
cask "blockbench"
cask "discord"
cask "betterdiscord-installer"
cask "slack"
cask "signal"
cask "deepl"
cask "zoom"
cask "gyazo"
cask "spotify"
cask "obs"
cask "steam"
cask "epic-games"
cask "unity-hub"
cask "minecraft"
cask "adobe-creative-cloud"
cask "figma"
cask "canva"
cask "miro"
cask "notion"

cask "font-fira-code"
cask "adoptopenjdk/openjdk/adoptopenjdk8"
cask "khanhas/tap/spicetify-cli"

mas "Xcode", id: 497799835
mas "Craft", id: 1487937127
mas "TweetDeck", id: 485812721
mas "NordVPN", id: 905953485