tap "homebrew/cask"
tap "homebrew/cask-fonts"
cask_args appdir: "/Applications"

brew "stow"
brew "gpg"
brew "asdf"
brew "coreutils"
brew "curl"
brew "git"
brew "starship"
brew "ffmpeg"

cask "google-japanese-ime"
cask "google-chrome"
cask "alfred"
cask "1password"
cask "visual-studio-code"
cask "iterm2"
cask "docker"
cask "discord"
cask "slack"
cask "signal"
cask "obs"
cask "figma"
cask "minecraft"
cask "notion"