#!/bin/sh

set -e

log() {
    message=$1
    echo 🚀 "$message"
}

is_file() {
    path="$1"
    [ -f "$path" ]
}

is_dir() {
    path="$1"
    [ -d "$path" ]
}

if ! is_file /opt/homebrew/bin/brew; then
    log 'Setup Homebrew'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
    log 'Install Rosetta 2'
    sudo softwareupdate --install-rosetta
fi

if ! is_dir ~/dotfiles; then
    log 'Clone dotfiles'
    cd ~
    git clone git@github.com:yutakobayashidev/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

log 'Link dotfiles'
if ! is_dir ~/.config; then
    mkdir ~/.config
fi

stow -v -d ~/dotfiles/packages -t ~ zsh starship asdf

# macOS settings

~/dotfiles/macos-setting

# asdf

for plugin in $(awk '{print $1}' ~/.tool-versions); do
    if ! is_dir ~/.asdf/plugins/"$plugin"; then
        asdf plugin add "$plugin"
    fi
done

is_runtime_versions_changed () {
    plugin="$1"
    specified=$(grep "$plugin" ~/.tool-versions | awk '{$1=""; print $0}')
    installed=$(asdf list "$plugin" 2>&1)

    is_changed=
    for version in $specified; do
        match=$(echo "$installed" | grep "$version")
        [ -z "$match" ] && is_changed=1
    done

    [ "$is_changed" ]
}

for plugin in $(asdf plugin list); do
    if is_runtime_versions_changed "$plugin"; then
        log "Install runtime: $plugin"
        asdf install "$plugin"
    fi
done