#!/bin/sh

echo 🔨 Configuring macOS default settings

###########################################################
# General
###########################################################

# Disable the “Are you sure you want to open this application?” dialog

dfaults wreite com.apple.LaunchServices LSQuarantine -bool false

###########################################################
# Finder
###########################################################

# Change the default directory name to English.

rm ~/Downloads/.localized | rm ~/Documents/.localized | rm ~/Applications/.localized | rm ~/Desktop/.localized | rm ~/Library/.localized | rm ~/Movies/.localized | rm ~/Pictures/.localized | rm ~/Music/.localized | rm ~/Public/.

# Show all file extensions inside the Finder

defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"

# Disable the warning before emptying the Trash

defaults write com.apple.finder WarnOnEmptyTrash -bool false

###########################################################
# Dock
###########################################################

# Auto-hide the Dock

defaults write com.apple.dock autohide -bool true

# Time until the dock appears.

defaults write com.apple.dock autohide-delay -float 0;

# Remove the Dock autohide animation

defaults write com.apple.dock "autohide-time-modifier" -float "0"

###########################################################
# Screenshot
###########################################################

# Change the first file name to English.

defaults write com.apple.screencapture name screenshots

# Change the screenshot extension to jpg

defaults write com.apple.screencapture type jpg

# Create a directory to save the screenshots.

mkdir ~/Pictures/screenshots/

# Set default screenshot location.

defaults write com.apple.screencapture "location" -string "~/Pictures/screenshots"

###########################################################
# reboot
###########################################################

# Finder

killall Finder


# menu bar

killall SystemUIServer

# dock

killall Dock