name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run dotfiles
      run: ${GITHUB_WORKSPACE}/packages/cli/scripts/dotfiles

    - name: Load .zshrc
      run: |
        bash ~/packages/terminal/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi