name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: cleaning
      run: |
        rm /usr/local/bin/aws
        rm /usr/local/bin/aws_completer
        rm /usr/local/bin/pod
        rm /usr/local/bin/go
        rm /usr/local/bin/gofmt
        rm "$HOME/.gitconfig"

    - name: Run dotfiles
      run: ${GITHUB_WORKSPACE}/packages/cli/scripts/dotfiles

   #  - name: Load .zshrc
   #    run: |
   #     zsh ~/packages/terminal/.zshrc 2> error.log; cat error.log
   #     if [ -s error.log ]; then false; fi
    
    - name: post status to Discord
      if: always()
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "Checking the quality of dotfiles"
        username: GitHub Actions
        avatar_url: ${{ secrets.AVATAR_URL }}