name: macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: cleaning
      run: |
        rm /usr/local/bin/aws
        rm /usr/local/bin/aws_completer
        rm /usr/local/bin/pod
        rm "$HOME/.gitconfig"
        rm "$HOME/.zshrc"

    - name: Run dotfiles
      run: ${GITHUB_WORKSPACE}/packages/cli/scripts/dotfiles

    - name: Load .zshrc
      run: |
        zsh ~/packages/terminal/.zshrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Discord notifications
      run: ${GITHUB_WORKSPACE}/packages/cli/scripts/dotfiles

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
